Public Class MasterPerkiraanNew
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        SqlDataSource1.Fill()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        SqlDataSource2.Fill()
        SqlDataSource3.Fill()
        SqlDataSource4.Fill()
        SqlDataSource5.Fill()
        SqlDataSource6.Fill()
        SqlDataSource7.Fill()
        SqlDataSource8.Fill()
    End Sub
End Class